export const dataSource=[
    {
        id:"0",
        userName:"lily",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"1",
        userName:"wang",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"2",
        userName:"jack",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"3",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"4",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    }, {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    }, {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    }, {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    }, {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    },
    {
        id:"5",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    }
]
export const columns=[
    {
        title:"id",
        dataIndex:"id",
        width:80
    },
    {
        title:"用户名",
        dataIndex:"userName",
        width:80
    },
    {
        title:"性别",
        dataIndex:"sex",
        width:80,
        render(sex){
            return sex===1?"男":"女"
        }
    },
    {
        title:"state",
        dataIndex:"state",
        render(state){
            let config={
                "1":"风华浪子"
            }
            return config[state]
        },
        width:80
    },
    {
        title:"兴趣",
        dataIndex:"interest",
        width:80
    },
    {
        title:"生日",
        dataIndex:"birthdayL",
        width:80
    },
    {
        title:"地址",
        dataIndex:"address",
        width:120
    },
    {
        title:"时间",
        dataIndex:"time",
        width:120
    }
]
export const columns2=[
    {
        title:"id",
        dataIndex:"id",
        fixed:"left",
        width:80
    },
    {
        title:"用户名",
        dataIndex:"userName",
        fixed:"left",
        width:80
    },
    {
        title:"性别",
        dataIndex:"sex",
        width:80,
        render(sex){
            return sex===1?"男":"女"
        }
    },
    {
        title:"state",
        dataIndex:"state",
        render(state){
            let config={
                "1":"风华浪子"
            }
            return config[state]
        },
        width:80
    },
    {
        title:"兴趣",
        dataIndex:"interest",
        width:80
    },
    {
        title:"生日",
        dataIndex:"birthdayL",
        width:80
    },
    {
        title:"地址",
        dataIndex:"address",
        width:120
    },
    {
        title:"时间",
        dataIndex:"time",
        width:120
    },
    {
        title:"时间",
        dataIndex:"time",
        width:120
    },
    {
        title:"时间",
        dataIndex:"time",
        width:120
    },
    {
        title:"时间",
        dataIndex:"time",
        width:120
    },
    {
        title:"时间",
        dataIndex:"time",
        width:120
    },
    {
        title:"时间",
        dataIndex:"time",
        width:120
    },
    {
        title:"时间",
        dataIndex:"time",
        fixed:"right",
        width:120
    }
]
export const columns3=[
    {
        title:"id",
        dataIndex:"id",
        fixed:"left",
        width:80
    },
    {
        title:"用户名",
        dataIndex:"userName",
        fixed:"left",
        width:80
    },
    {
        title:"性别",
        dataIndex:"sex",
        width:80,
        render(sex){
            return sex===1?"男":"女"
        }
    },
    {
        title:"state",
        dataIndex:"state",
        render(state){
            let config={
                "1":"风华浪子"
            }
            return config[state]
        },
        width:80
    },
    {
        title:"兴趣",
        dataIndex:"interest",
        width:80
    },
    {
        title:"生日",
        dataIndex:"birthdayL",
        width:80
    },
    {
        title:"地址",
        dataIndex:"address",
        width:120
    },
    {
        title:"时间",
        dataIndex:"time",
        width:120
    },
    {
        title:"年龄",
        dataIndex:"age",
        width:120,
        sorter:(a,b)=>{
            return a.age-b.age
        }
    }
]
export const dataSource3=[
    {
        id:"0",
        userName:"lily",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00",
        age:"18",
    },
    {
        id:"1",
        userName:"wang",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00",
        age:"20",
    },
    {
        id:"2",
        userName:"jack",
        sex:"1",
        state:"1",
        interest:"1",
        birthdayL:"2000-1-1-",
        address:"杭州市",age:"15",
        time:"8:00"
    },
    {
        id:"3",
        userName:"poss",
        sex:"1",
        state:"1",
        interest:"1",age:"12",
        birthdayL:"2000-1-1-",
        address:"杭州市",
        time:"8:00"
    }
]